### ISSUE TITLE
Question about trajectory waypoints tracking

### ISSUE THREAD

**Issue by jamesjingqili** [tg623623nana/Distributed-Multi-agent-Interaction-Generation-with-Imagined-Potential-Games#1]
I wonder if the current code supports tracking a sequence of waypoints? I tried to define this MPC problem by defining time-varying costs, but it seems that the time t enters the automatic differentiation and therefore we cannot use time t to encode different waypoints at each time. I wonder if there is any way to remove the time t from entering the automatic differentiation? Thanks!

**Comment by tg623623nana** [comment]
The current code does not support tracking a sequence of waypoints. This is because the goal is explicit under our scenario setting, so we only need to set one goal point for the problem. 

However, if you want to input the target state as a sequence of waypoints, you can simply achieve it with 2 steps without removing the time t from automatic differentiation. 

1. First create your target state in shape (horizon, state_dimension)
2. Modify the iLQR solver cost function and equality constraint as below   
 ``` modify python
''' State cost part in cost function '''
# from 
(x - target) * Q  * (x - target) 
# to
( x - target[t, :] ) * Q  * ( x - target[t, :] ) 

''' Terminal constraint part in equality constraint '''
# from 
error = x - target
# to 
error = x - target[t, :]
 ```
Please note that the terminal constraint will only work when `time == horizon`.
    
    
I also built a demo in new branch 'experimental' to show the implementation. You can find 
1. How to decide the target state in `simulation.py -> demo_timeVaryingGoal_2_agents()`
2. How to modify the iLQR solver in `ilqr_trajectory_planner.py -> solve_IPG_timeVaryingGoal()`

In the demo, I have set two waypoints represented as 'X' for each agent. All the blue 'X' represent the targets for the blue agent, and all the green 'X' represent the targets for the green agent. The first waypoint serves as the target from `t = 0 to t = horizon / 2`, and the second waypoint serves as the target from `t = horizon / 2 + 1 to t = horizon`. The first waypoint will be updated with the state at t = horizon / 2 in the current planning when the agent achieves it.
The result of the demo is as following,
![image](https://github.com/tg623623nana/Distributed-Multi-agent-Interaction-Generation-with-Imagined-Potential-Games/blob/experimental/ilqr_trajectory_optimization_planning/figs/2_agent_IPG_TimeVaryingGoal/demo.gif?raw=true)

Hope this help!

**Comment by jamesjingqili** [comment]
Thank you very much!
